version: 1

goos: freebsd
goarch: arm

main: ./
binary: hello-{{ .Os }}-{{ .Arch }}6

env:
  - CGO_ENABLED=0
  - GOARM=6

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - "-extldflags \"-static\""
  - "-X main.version={{ .Env.VERSION }}"
