version: 1

goos: linux
goarch: amd64

main: ./
binary: hello-{{ .Os }}-{{ .Arch }}

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - "-extldflags \"-static\""
  - "-X main.version={{ .Env.VERSION }}"
