version: 1

goos: netbsd
goarch: arm

main: ./
binary: hello-{{ .Os }}-{{ .Arch }}6

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GOARM=6

flags:
  - -trimpath
  - -tags=netgo

ldflags:
  - "-w"
  - "-s"
  - "-extldflags \"-static\""
  - "-X main.version={{ .Env.VERSION }}"
