version: 1

goos: windows
goarch: arm

main: ./
binary: hello-{{ .Os }}-{{ .Arch }}7.exe

env:
  - CGO_ENABLED=0
  - GOARM=7

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - "-extldflags \"-static\""
  - "-X main.version={{ .Env.VERSION }}"
