name: SLSA

on: push

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.10.0
    strategy:
      matrix:
        os:
          - linux
          # - windows
          # - darwin
          # - freebsd
          # - openbsd
          # - netbsd
        arch:
          # - 386
          # - amd64
          - arm7
          # - arm64
        include:
          - os: linux
            arch: ppc64
          - os: linux
            arch: ppc64le
          - os: linux
            arch: riscv64
          - os: linux
            arch: s390x
        exclude:
          - os: darwin
            arch: 386
          - os: darwin
            arch: arm7
    with:
      go-version-file: ./go.mod
      config-file: .github/targets/${{matrix.os}}-${{matrix.arch}}.yaml
      evaluated-envs: "VERSION:v0.0.0"
      draft-release: true
      upload-assets: true
      upload-tag-name: v0.0.0

  list:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # builder_go_slsa3.yml@v1.10.0 uses upload-artifact@v3
    # So, we have to use v3 to download artifact.
    # See https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md
    - uses: actions/download-artifact@v3
    - run: ls -R
